### ISSUE TITLE
Link to skills in the tab bar of profile page is broken

### ISSUE THREAD

**Issue by jungomi** [jocelynthode/coachup#100]
**Description :**
* We discussed to remove the tab bar entirely. So either fix the link or remove it.

**Priority :** Low
**Reviewer :** 

**Effort Planned :** 0.5
**Actual Effort :** 0.5

**Comment by liechtia** [comment]
3480291c2bae860a56a07b0408dcc8fbae251988
509f7b1b94d62524fb390f0c3ed4858941c4a288

**Comment by jocelynthode** [comment]
Seems fine. Since I'm using the tab view, we'll have to see how to merge it
