### ISSUE TITLE
UX issues with courses views

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#102]
- [x] don't show apply button when current_user = course.coach
- [x] show edit/delete button when current_user = course.coach
- [x] can't click on a coach username to go to his profile
- [x] user profile: add a link to this user's taught courses
- [x] It would be nice if the whole colored part of a course card was a link to the show view (and not just the icon)
- [x] display newlines in course description on the show view ?

**Comment by jocelynthode** [comment]
https://github.com/jocelynthode/coachup/commits/ux_issues commits on 1st December by me
