### ISSUE TITLE
upcoming sessions show sessions that already occurred

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#104]
Description :
Remove old events in upcoming sessions
Priority : Low
Reviewer : @jungomi 

Effort Planned : 1h
Actual Effort : 0.5h

**Comment by amand4msk** [comment]
75ca01057be12f8a83dad8daafa946ccda5447e4

**Comment by jungomi** [comment]
Changed to compare the start_time to the current time. 28cacb7308a5424dec67d10cb6f465e9ab455216
