### ISSUE TITLE
The map sometimes doesn't show when editing course

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#109]
When you edit a course, submit the form with a wrong value (i.e. wrong ends_at), the course edit form renders again but the map doesn't work this time.
This may be related to #80 and turbolinks.
In the worst case, we can redirect to the course edit form instead of rendering (worse UX but it should work).

**Comment by simonbru** [comment]
3283b78bf61789b1a2b42950c8b5731a952d5e8a
I fixed the gmap loading issue ( #80 ) and fill the gmap widget with data from the course/location model. This means the disabled text input containing the address has become redundant, which is why I removed it.

**Comment by simonbru** [comment]
I put the issue out of review because I noticed two more problems to fix:
* use render instead of redirect_to when submitting the form fails
* don't show multiple markers when changin the location
533319bb4969440a10a5619762c2961df77c079c

**Comment by jungomi** [comment]
The map works well and does not seem to break any more.

**Comment by simonbru** [comment]
Thanks, I will merge then

**Comment by jungomi** [comment]
I did look at the code, not too carefully, but everything looked fine.
