### ISSUE TITLE
display training sessions in the course show view (and start time ?)

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#110]
**Description :**
* display traininng sessions in course show view

**Priority :** High
**Reviewer :** 

**Effort Planned :** 1.5
**Actual Effort :** 1.5

**Comment by liechtia** [comment]
60aba7162856162540fe9846d7a02d59417fd086

**Comment by jungomi** [comment]
Replaced count method with size 7721aba6dc0befb82dc54c6fc61e03f693b11002
See https://github.com/bbatsov/ruby-style-guide#count-vs-size

**Comment by simonbru** [comment]
It already merged but the issue isn't closed so I don't open a new one:
It shows some training sessions occuring after the end date (similar issue as the one we had with upcoming_training_sessions)
