### ISSUE TITLE
Improve 'my coaches' and 'users index' views

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#114]
Description :
Create the same view (partial) for my coaches, users profile and my partnerships 
Priority : Low
Reviewer : @jungomi , @simonbru 

Effort Planned : 1h
Actual Effort : 1h

**Comment by amand4msk** [comment]
746d9474e7542c1d98a699db3bf4765b0980500f
3fc023b5f473a2472e9718b67fffc49f49ac268d

**Comment by simonbru** [comment]
Nice, looks pretty cool as usual ! :)

I pushed the following changes on your branch: 
* merged some parts of your views into a partial as we discussed
* reviewed your code and applied some fixes (e63613907319130557ba0efa368e7219912b9975)
* modifed partnerships index view to reuse your code (I gave up the *Unfollow* button on the index view for simplicity)

I saw a problem when there are too many profiles on the same page, it is basically the same problem we have on the courses index view and the profile page. I don't know if we will ever be able to fix it...
![capture d ecran de 2015-12-07 17-10-31](https://cloud.githubusercontent.com/assets/2358343/11632441/7333544c-9d07-11e5-90fd-57c18e6739e7.png)

Also, I have a small suggestion: What do you think about using ```$brand-primary``` (the shade of blue used in bootstrap's theme) for the card's background colour instead of *royalblue" ? It looks slightly more coherent with the overall theme in my opinion:
![capture d ecran de 2015-12-07 17-34-08](https://cloud.githubusercontent.com/assets/2358343/11632877/0ebfaa90-9d09-11e5-8082-4537698ed059.png)

**Comment by simonbru** [comment]
I'll take that as a "yes" ;)
