### ISSUE TITLE
Create user model with CyberCoach

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#18]
**Description :** Create a a user model using data from CyberCoach
**Priority :** High
**Reviewer :** @jocelynthode
**Effort Planned :** 3h

**Actual Effort :** 3h

**Comment by jungomi** [comment]
Change from devise model to a model using the CyberCoach service directly.
Moving to Sprint 2.

**Comment by jungomi** [comment]
See [user.rb](https://github.com/jocelynthode/coachup/blob/315fadc881ca3f93907d15c8f3d9d887b6640aeb/coachup/app/models/user.rb) from 315fadc881ca3f93907d15c8f3d9d887b6640aeb

**Comment by jocelynthode** [comment]
Looks fine
