### ISSUE TITLE
add maps to courses

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#21]
**Description :** Display a map into a course
**Priority :** Medium
**Reviewer :** @jocelynthode 
**Effort Planned :** 6h

**Actual Effort :** 8h

**Comment by simonbru** [comment]
Just in case, when we generated the training session model, we added two columns for the latitude and longitude in a way that is compliant with this gem: http://www.sitepoint.com/use-google-maps-rails/
It does not mean that we have to use it though.
