### ISSUE TITLE
add calendar export to course & calendar

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#22]
**Description :** Export training sessions to google calendar

**Priority :** Medium

**Reviewer :** Andrea

**Effort Planned :** 4h

**Actual Effort :** 4h

**Comment by jungomi** [comment]
mostly d53d4a30451b625f4e09616a06e1b899c42e70a2 and 2fa8464d42262781fc0afe3646325c115a680d17

Each traning session takes 1 hour for now, since end time seems to be messed up between course and sessions.
