### ISSUE TITLE
functionality to form partnership

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#23]
**Description :** 
* Create a model to represent partnerships and work with them
* Create buttons to create/remove partnerships (toggle button)

EDIT: The buttons only show the state of the partnership for now, I suggest to wait for @mengja's code to be merged first, since I'll have to add some code in his controller for this feature.

**Priority :** Medium

**Reviewer :** @mengja 

**Effort Planned :** 4h

**Actual Effort :** 8h

**Comment by simonbru** [comment]
7cffd706e5c467f439179f01163c621785f72047
