### ISSUE TITLE
Edit taught courses

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#26]
**Description :** Add the possibility for a coach to edit his course
* Edit the course informations
* ~~Edit the start date and move all training sessions accordingly~~

**Priority :** Medium

**Reviewer :** 

**Effort Planned :** 4h

**Actual Effort :** 3h

**Comment by jocelynthode** [comment]
We decided to get rid of the functionality to edit the training sessions

**Comment by jocelynthode** [comment]
6ab1938ba40b0e4482bc7038dd30a8aabd9cafc8
6a42e0a06efa9f1b287178eb6709bc635e471513

What must still be done(by @amand4msk ) : 
* Integrate Maps into the partial
* create the table location and the foreign key to link courses and the location table
* add fields to create training sessions ( @liechtia will probably do that you can pull my code)
