### ISSUE TITLE
rating of coaches

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#31]
**Description :** Add the possibility for a user to rate an other user

**Priority :** Medium

**Reviewer :** 

**Effort Planned :** 2h

**Actual Effort :**

**Comment by liechtia** [comment]
remove rating?? 
adding comment to rating??

**Comment by jocelynthode** [comment]
No Comment, just a like/dislike kinda rating and we show the percentage of approval

**Comment by jocelynthode** [comment]
45a03f016bf90be67019e0e542cd90857d037173

09fe8aa2b14117ca2620f54cdd2af28883146848

240161d0ea0f9cab63802731519d7c3cdde73bd0

**Comment by jocelynthode** [comment]
I'm waiting on Simon to see how we could check that the user can't rate a coach he hasn't trained with
