### ISSUE TITLE
E-mail system

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#32]
**Description :** 
* Implement a way to send emails from elsewhere in the code
* We could probably use sendgrid as the mail relay

**Priority :** High

**Reviewer :** 

**Effort Planned :** 

**Actual Effort :**

**Comment by simonbru** [comment]
cfea3c0c1c7b69eac0101ff7b36a89c197c9fd42
I used ActionMailer for the mail system, sendgrid for the SMTP relay and dotenv to load sendgrid credentials from a .env file while in development mode

This branch (mail-system) is already based on the add_del-training-sessions branch

**Comment by jocelynthode** [comment]
Reviewed
