### ISSUE TITLE
wrong paths in the gitignore file

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#50]
The gitignore file present in the root of the repo defines some absolute paths that were right for the bike-trader project but not for coachup.
For example:
```
/log
/tmp
/db/*.sqlite3
/db/*.sqlite3-journal
/public/system
/coverage/
/spec/tmp
```
These rules don't serve any purpose since the rails projet is in the coachup subfolder.
Some of these rules are also present in a second gitignore file in the coachup subfolder (and there are useful there).

I suggest that we keep the root gitignore file for rules that apply anywhere in the repo, and we just move the other rules to the gitignore file in the coachup subfolder.

BTW It may be nice to merge this quickly in the dev branch to avoid people committing wrong files by accident.

**Comment by jocelynthode** [comment]
My bad , I should have checked it. Can you correct it and push it to the dev and master branch please ?

Also everyone should then pull from dev in their branch to avoid some later merge conflict

Le 13 octobre 2015 19:21:54 GMT+02:00, simonbru <notifications@github.com> a écrit :
>The gitignore file present in the root of the repo defines some
>absolute paths that were right for the bike-trader project but not for
>coachup.
>For example:
>```
>/log
>/tmp
>/db/*.sqlite3
>/db/*.sqlite3-journal
>/public/system
>/coverage/
>/spec/tmp
>```
>These rules don't serve any purpose since the rails projet is in the
>coachup subfolder.
>Some of these rules are also present in a second gitignore file in the
>coachup subfolder (and there are useful there).
>
>I suggest that we keep the root gitignore file for rules that apply
>anywhere in the repo, and we just move the other rules to the gitignore
>file in the coachup subfolder.
>
>BTW It may be nice to merge this quickly in the dev branch to avoid
>people committing wrong files by accident.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jocelynthode/coachup/issues/50

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by simonbru** [comment]
Ok ok, I will do it now then.
I am not sure if some path should be ignored in the root or in the project folder, because it may depend of e.g. whether you choose to open the root folder or the subfolder in rubymine.
I suppose it doesn't hurt to ignore them in both places
