### ISSUE TITLE
JS error when the page loads in sb-admin-2.js

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#53]
This error happens at the loading of each page:
```
TypeError: $(...).metisMenu is not a function
```
We probably need to add a gem for metisMenu or add the code ourselves in app assets.
This doesn't cause any real issue now, but we will probably need it if we want to have a multi-level menu in the left pane.

**Comment by simonbru** [comment]
306290eadeae1f9cecf89f3f5ef5794d1a97e212

Note: I tried to quickly do a tree menu to check if it actually works but it was frustrating and this already is the work for another issue.

**Comment by jocelynthode** [comment]
Since you only added the js library for metis-menu you can push it to dev
