### ISSUE TITLE
Flash notices for login appear at the bottom of the page

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#54]
![cap](https://cloud.githubusercontent.com/assets/2358343/10592515/db258a50-76bc-11e5-82d6-82bbe02a8b87.png)

If the code for flash notices is coming from / only used by devise, then we can probably ignore this issue since we said we would get rid of devise.

**Comment by simonbru** [comment]
7e037512eda39968a0a3e4c41c539a40fa43b8e8

**Comment by jocelynthode** [comment]
Working for me so I think you can merge into dev
