### ISSUE TITLE
show coach name instead of id in course overview views

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#55]
**Description :**
* show coach name instead of id

**Priority :** Medium
**Reviewer :** Michael

**Effort Planned :** 0
**Actual Effort :** 0

**Comment by mengja** [comment]
872814c63f9ad5de1e08d89ef60b8cb13053ea65

**Comment by liechtia** [comment]
@mengja i have the same problem and need to correct this bug too in my code...

**Comment by liechtia** [comment]
01f2fc06c47f9a98b029a8e0b59fbc70dd7bde59
