### ISSUE TITLE
merge profiles and users controllers and views ?

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#61]
I feel it would be more RESTful to have the show and index methods of the "users" resource display the users profiles instead of having this functionality in a second controller with a similar name.
Right now the index and show methods of users_controller seem to be there for debugging purposes (and it's fine for now), but maybe we should discuss about this "issue" at some point.

**Comment by simonbru** [comment]
9ae7fece7b56869ca8d8473433e4db2d7bea3483
There are still some routes related to users that should refactored in my opinion, but I don't think they are related to this issue so I let them as is for now.

**Comment by jungomi** [comment]
That looks good, but we should decide if we want to keep the user index or simply remove it. If we keep it we need to make it somewhat pretty.
