### ISSUE TITLE
courses_by_my_coaches find better solution

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#63]
**Description :**  after issue #23 is in development branch, update courses_controller so that courses_by_my_coaches uses partnerships correctly

**Priority :** high

**Reviewer :** @simonbru 

**Effort Planned :** 1h

**Actual Effort :** 1h

**Comment by liechtia** [comment]
37b94aba918ae41b7aba3a7aee3295ae32df02cf

**Comment by simonbru** [comment]
It is working fine.
I think you don't need `if partnership.present?` at line 78 though, and at lines 68 to 70 you can replace @user by `user` (a local variable is enough)
