### ISSUE TITLE
Add actions in partnerships controller to allow users to follow/unfollow a user

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#64]
As I explained in #23, I had to create a partnerships controller and @mengja already had created one in his issue. Now I am able to add a create and a destroy action and it should be quick to do. (It may be worth it to do it before sprint 3)

**Comment by simonbru** [comment]
done: fab0220aa2e41cc90857bd93d950f4657d7e8662
I also added a follow/unfollow button on the partnerships index view. 
I renamed a method in the partnership model since I don't think anybody else uses it this sprint.

**Comment by jocelynthode** [comment]
Reviewed
