### ISSUE TITLE
Improve partnership overview to display names

### ISSUE THREAD

**Issue by mengja** [jocelynthode/coachup#71]
**Description :**
* Improve Partnership Overview

**Priority :** High
**Reviewer :** 

**Effort Planned :** 
**Actual Effort :**

**Comment by simonbru** [comment]
7e5ebce76956a5b8d37eac2b4ecc74bee7da7270
This has already been merged in the development branch.
The initial work has been done by fisnik and I fixed some issues.

**Comment by jocelynthode** [comment]
Reviewed
