### ISSUE TITLE
create training sessions

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#72]
**Description :**
* when a course is created the coach should be able to create training sessions
* training session can be deleted only before course start
* display training sessions collapsed by default

**Priority :** High
**Reviewer :** 

**Effort Planned :**  3h
**Actual Effort :**

**Comment by jocelynthode** [comment]
I have to check if the start and end date are working as intended

**Comment by jocelynthode** [comment]
Delete training sessions should be done in the edit part instead of here @amand4msk as I think this makes more sense. BTW we can't really delete training sessions right now as we didn't focus on single training sessions here.

**Comment by jocelynthode** [comment]
Too much commits to link one. I'll link the files that were modify. You can look at the history to see the cahnges : 
* https://github.com/jocelynthode/coachup/blob/eccb74cdecbb5eec24ec3ea196723bfa3bf62f38/coachup/app/views/courses/_form.html.erb

* https://github.com/jocelynthode/coachup/blob/eccb74cdecbb5eec24ec3ea196723bfa3bf62f38/coachup/app/models/course.rb
