### ISSUE TITLE
Figure out how to create entries when training sessions end

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#75]
**Description :** 
When a training session has ended, we are supposed to create an entry on CyberCoach (for each participant ?).
We have to create some kind of CRON job on heroku do check that, or maybe do it at the same time as any request on our app.

**Priority :** Medium

**Reviewer :** 

**Effort Planned :** 

**Actual Effort :**

**Comment by simonbru** [comment]
I took a look at the options we had to schedule tasks on Heroku for free, and it seems that the *Heroku scheduler* that we first wanted to try works fine.
I tried to send emails hourly for 24h to check if the scheduler was somehow impacted by free dynos limitations (6h of sleep min per day) and I didn't see any issue.
Even though the scheduler is *best effort*, most emails arrived around the right time.
![capture d ecran de 2015-11-12 23-31-02](https://cloud.githubusercontent.com/assets/2358343/11133483/4762bd00-8996-11e5-9ea9-6a0f6f3a4ada.png)

**Comment by simonbru** [comment]
b8dae1c0c8e1eb665923b0e33d59f598f3edf5db
This is only a WIP, we will probably need to take another approach

**Comment by jocelynthode** [comment]
Switched to Sprint 4 as it's a WIP

**Comment by simonbru** [comment]
706d9bfc87f42045fd4c50d0c7dc16d35188f102
This should work now (finally!)
We will have to register a daily cron job on the heroku scheduler for this task.

**Comment by simonbru** [comment]
It is merged:
0f1a7ad7c6b76e3e6808cf6e7235db10f0d2a5a5

However I keep this issue until we deploy on heroku in order not to forget to add a cron job on there.
