### ISSUE TITLE
when applying for a course, subscribe user to the cybercoach sport

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#79]
**Description :**
* subscribe to sport when applying for course

**Priority :** High
**Reviewer :** @simonbru 

**Effort Planned :** 1h
**Actual Effort :** 2h

**Comment by liechtia** [comment]
6355a31a96cb06c71957db61ca67d54b65506921
e3d1f64654725367d499f4c6398037759de5d645

**Comment by liechtia** [comment]
the first commit is already in development branch, but the fix (second commit) is not...

**Comment by simonbru** [comment]
I think this part in CourseController.apply is now useless:
```
    rescue RestClient::Exception => exception
      exception
    end
```
since you already catch the exception in the rest_put method
