### ISSUE TITLE
Training session end date

### ISSUE THREAD

**Issue by jungomi** [jocelynthode/coachup#84]
The end date of the training sessions seems to be the end date of the course (for the first session) which is then extended in the recurring sessions to match the same duration.

We should probably add a field for the duration of one training sessions.

**Comment by jocelynthode** [comment]
Creating a field for the number of hours and just adding a field to the form letting the user choose would work for you ?

**Comment by jocelynthode** [comment]
43a34104046f4653efb443b9ad9c804a9c798361

**Comment by simonbru** [comment]
Since you added a duration field, it could be nice to include it in the cybercoach entryduration field when creating entries. I just write this here so we won't forget.
