### ISSUE TITLE
Hide Leave/Apply buttons depending on the situation

### ISSUE THREAD

**Issue by jocelynthode** [jocelynthode/coachup#86]
**Description :**
* Leave should only appear when you've applied to a site.
* Apply shoudl only appear when you've not yet applied and there is still room in the course

**Priority :** Medium
**Reviewer :** 
**Effort Planned :** 1
**Actual Effort :** 0.5

**Comment by liechtia** [comment]
b05250ab5a1011fa35927ee04b4c0cdf976d392e
