### ISSUE TITLE
Give the user the possibility to edit his/her profile picture

### ISSUE THREAD

**Issue by jocelynthode** [jocelynthode/coachup#87]
**Description :**
* Just modify the edit profile view and controller to include that
* If no picture is provided, take default picture
* deleting the picture

**Priority :** High
**Reviewer :** 
**Effort Planned :** 3
**Actual Effort :** 8

**Comment by liechtia** [comment]
after trying for 8 hours, i decided there will be no default picture

**Comment by liechtia** [comment]
d692d2b170c8fac0e3735d2587c2dd9625cf77d2

**Comment by liechtia** [comment]
c9ed74e5ce1eef6882fc9400755f6c0dc4fd4898

**Comment by liechtia** [comment]
default picture now directly added in the view
