### ISSUE TITLE
Implement the datefield as a datepicker

### ISSUE THREAD

**Issue by jocelynthode** [jocelynthode/coachup#89]
This way it's working also on Firefox for example.

**Comment by jungomi** [comment]
11f71183e0415cc8b84b8155cc6ab8e27f56ca65

**Comment by jocelynthode** [comment]
Date is not stored in the db. Actually no fields are stored in the db at the moment.

**Comment by jungomi** [comment]
26b67a02827de407b06a6d45e13d2d03fe9a96a5

**Comment by jocelynthode** [comment]
Reviewed
