### ISSUE TITLE
Rollback databases update/insert if cybercoach request fails

### ISSUE THREAD

**Issue by jocelynthode** [jocelynthode/coachup#96]

**Comment by simonbru** [comment]
530ae2654f593c78898e85962f0a829db2fd373e

**Comment by simonbru** [comment]
I forgot to use transactions for course.apply and course.update

**Comment by simonbru** [comment]
2527d971a5178c9874eb9da29aa646c21db30231
I tested it and already pushed it, but it may be a good idea for someone else to review it too.

**Comment by simonbru** [comment]
jocelyn did the second review
