### ISSUE TITLE
Give the possibility to link a facebook profile to your account

### ISSUE THREAD

**Issue by simonbru** [jocelynthode/coachup#99]

**Comment by simonbru** [comment]
7f696e77b62a67e8cf258229d47c08dfda45af9d

**Comment by simonbru** [comment]
By the way, since the app is not reviewed by facebook, you have to be a "developer/tester" of the facebook app to test it.

**Comment by jungomi** [comment]
Simon made the app public and can now be used with a regular facebook account.
